#!/bin/sh 

mongodb_port=27017
mongodb_username="root" 
mongodb_password="" 

function_start_mongodb() 
{ 
    printf "Starting MongoDB...\n" 
    /usr/local/mongodb/bin/mongod --fork --dbpath /data/mongo_data --logpath /var/log/mongodb.log --port ${mongodb_port} --bind_ip=127.0.0.1
} 

function_stop_mongodb() 
{ 
    printf "Stoping MongoDB...\n" 
    /usr/local/mongodb/bin/mongod --dbpath /data/mongo_data --shutdown 
} 

 function_restart_mongodb() 
 { 
    printf "Restarting MongoDB...\n" 
    function_stop_mongodb 
    sleep 5 
    function_start_mongodb 
 } 


 if [ "$1" = "start" ]; then 
function_start_mongodb 
 elif [ "$1" = "stop" ]; then 
function_stop_mongodb 
 elif [ "$1" = "restart" ]; then 
 function_restart_mongodb 
 else 
 printf "Usage: /usr/local/mongodb/${mongodb_port}/mongodb {start|stop|restart}\n"
fi
